name: Update Helium Browser
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
jobs:
  update-helium-browser:
    name: Update Helium Browser
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Check if update is needed
        id: check
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          .github/update.sh --ci --only-check
      - name: Install Nix
        if: steps.check.outputs.should_update == 'true'
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: Update versions
        id: update
        if: steps.check.outputs.should_update == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          .github/update.sh --ci
      - name: Commit changes
        id: commit
        if: steps.check.outputs.should_update == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "${{ steps.update.outputs.commit_message }}"
          file_pattern: "*"
